swagger: '2.0'
info:
  title: 'Test Kuantaz'
  description: ''
  version: '0.1'

definitions:
  Institution:
    type: object
    required:
      - name
      - description
      - address
    properties:
      name:
        type: string
        maxLength: 255
      description:
        type: string
        maxLength: 255
      address:
        type: string
        maxLength: 255
  InstitutionForUpdate:
    type: object
    properties:
      name:
        type: string
        maxLength: 255
      description:
        type: string
        maxLength: 255
      address:
        type: string
        maxLength: 255
  InstitutionWithProject:
    type: object
    properties:
      name:
        type: string
        maxLength: 255
      description:
        type: string
        maxLength: 255
      address:
        type: string
        maxLength: 255
      projects:
        type: array
        items:
          $ref: "#/definitions/ProjectWithResponsibleUser"
  InstitutionWithAddress:
    type: object
    required:
      - name
      - description
      - address
      - address_google_maps
      - abbrev_name
    properties:
      name:
        type: string
        maxLength: 255
      description:
        type: string
        maxLength: 255
      address:
        type: string
        maxLength: 255
      address_google_maps:
        type: string
      abbrev_name:
        type: string
  Project:
    type: object
    required:
      - name
      - start_date
      - end_date
    properties:
      name:
        type: string
        maxLength: 255
      start_date:
        type: string
        format: date
      end_date:
        type: string
        format: date
  ProjectWithResponsibleUser:
    type: object
    properties:
      name:
        type: string
        maxLength: 255
      start_date:
        type: string
        format: date
      end_date:
        type: string
        format: date
      user:
        $ref: "#/definitions/User"
  ProjectWithDaysForEnd:
    type: object
    required:
      - name
      - start_date
      - end_date
    properties:
      name:
        type: string
        maxLength: 255
      count_days_for_end:
        type: integer
  User:
    type: object
    properties:
      name:
        type: string
        maxLength: 255
      surname:
        type: string
        maxLength: 255
      position:
        type: string
        maxLength: 255
      age:
        type: integer
      date_of_birth:
        type: string
        format: date
  UserWithProject:
    type: object
    properties:
      name:
        type: string
        maxLength: 255
      surname:
        type: string
        maxLength: 255
      position:
        type: string
        maxLength: 255
      age:
        type: integer
      date_of_birth:
        type: string
        format: date
      projects:
        type: array
        items:
          $ref: "#/definitions/Project"

  Message:
    type: object
    properties:
      message:
        type: string
  Error:
    type: object
    properties:
      error:
        type: string
