version: "3.8"
services:
  web:
    build: app
    ports:
      - "5000:5000"
    env_file:
      - app/.env.docker
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kuantaz
      - POSTGRES_PASSWORD=kuantaz
      - POSTGRES_DB=dbkuantaz
    expose:
      - 5432
volumes:
  postgres_data:
