swagger: '2.0'
info:
  title: 'Test Kuantaz'
  description: ''
  version: '0.1'

definitions:
  Institution:
    type: object
    required:
      - name
      - description
      - address
    properties:
      name:
        type: string
        maxLength: 255
      description:
        type: string
        maxLength: 255
      address:
        type: string
        maxLength: 255
  Project:
    type: object
    required:
      - name
      - start_date
      - end_date
    properties:
      name:
        type: string
        maxLength: 255
      description:
        type: date
      address:
        type: date
  Institution-with-address:
    type: object
    required:
      - name
      - description
      - address
      - address_google_maps
      - abbrev_name
    properties:
      name:
        type: string
        maxLength: 255
      description:
        type: string
        maxLength: 255
      address:
        type: string
        maxLength: 255
      address_google_maps:
        type: string
      abbrev_name:
        type: string
  Message:
    type: object
    properties:
      message:
        type: string
  Error:
    type: object
    properties:
      error:
        type: string